/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{js,jsx,ts,tsx}"],
  theme: {
    
    // overriden configs
    colors: {
      primary: {
        100: "#F1F8FF",
        light: "#F0F7FF",
        300: "#EAF4FF",
        400: "#D3E8FF",
        DEFAULT: "#185CAB",
        600: "#0B5EBE",
        900: "030712",
      },
      danger: {
        default: "#B11F3E",
        DEFAULT: "#B11F3E",
      },
      white: "#FFFFFF",
      black: "#000",
      success: {
        DEFAULT: "#28A745",
        "mid-light": "#9BE7AC",
        light: "#D8F6DF",
        "mid-dark": "#19692B",
        dark: "#145523",
      },
      info: "#185CAB",
      gray: {
        100: "#F3F4F6",
        200: "#E5E7EB",
        300: "#D1D5DB",
        DEFAULT: "#9CA3AF",
        500: "#6B7280",
        600: "#9D9597",
        border: "#E1E0E0",
        "border-line": "#D1D5DB",
        icon: "#374151",
        "icon-bg": "#E8E8E8",
      },
      alert: {
        DEFAULT: "#FFC107",
        "mid-light": "#FFF3CD",
        light: "#FFFAEC",
        "mid-dark": "#D39E00",
        dark: "#856404",
      },
      error: {
        DEFAULT: "#DC3545",
        "mid-light": "#FAE3E5",
        light: "#FCECED",
        "mid-dark": "#BD2130",
        dark: "#DC3545",
      },
      secondary: {
        DEFAULT: "#B11F3E",
        light: "#FF6182",
        "mid-light": "#FF94AB",
        "semi-light": "#FFC7D3",
        "tilt-light": "#FFFAFB",
        "btn-extend-assig": "#EE7505",
        "btn-success": "#22C55E",
        "error-message": "#B11F3E",
        "accept-btn": "#28A745",
        "reject-btn": "#FF4D4F",
        "info-message": "#FFF3CD",
        "alert-accepted": "#D8F6DF",
        "alert-rejected": "##FAE3E5",
        "batch-accept-text": "#117D42",
        "batch-accept-bg": "#DAF4E6",
        "batch-rejected-text": "#D26806",
        "batch-reject-bg": "#FFF5F2",
        "batch-select-text": "#185CAB",
        "batch-pending-text": "#374151",
        "batch-pending-bg": "#E5E7EB",
        "batch-warning-text": "#FF4D4F",
        "batch-warning-bg": "#FAE3E5 ",
        "input-field-bg": "#9CA3AF",
        "form-field": "#F3F4F6",
        "search-border": "#E1E0E0",
        "timeline-progress-bg": "#28A745",
        "image-slider-bg": "#E9F0F6",
        "search-list-sub-text": "#4B5563",
        "modal-bg": "rgba(0,0,0,0.5)",
        "select-field-arrow": "#4B5563",
        "password-icon": "#A3A3A3",
      },
    },
    borderRadius: {
      "r-small": "3px",
      "r-medium": "4px",
      "r-large": "5px",
      "circle-r": "9999px",
      "modal-radius": "25px",
      "batch-radius": "25px",
      "inputfield-radius": "8px",
    },
    // extended configs
    extend: {
      height: {
        input: "40px",
      },
      padding: {
        "container-screen-box": "16px",
        box: "10px",
        "block-thin-btn": "5px",
        "inline-thin-btn": "15px",
        "block-small-btn": "10px",
        "inline-small-btn": "20px",
        "block-large-btn": "10px",
        "inline-large-btn": "100px",
        "activity-list": "10px",
        "top-image-slider": "20px",
        "image-slider": "10px",
        "photo-comment": "15px",
        "top-photo-comment": "20px",
        "alert-message": "40px",
        "save-loading": "20px",
        "block-save-modal": "20px",
        "block-role-box": "15px",
        "inline-role-box": "30px",
        "block-textarea": "5px",
        "inline-textarea": "15px",
        "modals-regular": "15px",
        "inline-field": "15px",
        "block-field": "10px",
        "attendance-summary": "15px",
        "batch-x": "10px",
        "batch-y": "7px",
        "inline-icon": "23px",
        "block-icon": "20px",
        "icons-home": "20px",
      },
      fontSize: {
        xs: "8px",
        "body-micro": "10px",
        "body-xs": "12px",
        "body-sm": "13px",
        label: "14px",
        "header-sm": "15px",
        "header-md": "16px",
        "header-lg": "18px",
        "header-xl": "20px",
      },
      fontWeight: {
        "fw-md": "400",
        "fw-lg": "500",
        "fw-xl": "600",
      },
      borderWidth: {
        thin: "0.5px",
      },
    },
  },
  plugins: [],
}

